### ISSUE TITLE
Vehicle_fingerprint

### ISSUE THREAD

**Issue by vasaru** [ChristianKuehnel/bimmer_connected#31]
Here's the output of the vehicle_fingerprint script

[vehicle_fingerprint.zip](https://github.com/ChristianKuehnel/bimmer_connected/files/1759903/vehicle_fingerprint.zip)

**Comment by ChristianKuehnel** [comment]
Cool, thx. I added your files as test cases. I already found one bug: I did not parse the drive train for a plugin-hybrid correctly.
