### ISSUE TITLE
make it easier to test the library

### ISSUE THREAD

**Issue by m1n3rva** [ChristianKuehnel/bimmer_connected#47]
Based on the discussion in #41  we should make it easier for people to test the library and also contribute vehicle data. For that we should:
1. Add `requests` to the project dependencies
1. add documentation to pull the latest branch via pip

please assign this ticket to me, I'll prepare something

**Comment by lawtancool** [comment]
Maybe also specify a specific way/place to submit the files (should we use pull request, email, etc.)
