### ISSUE TITLE
Implement services in Home Assistant 

### ISSUE THREAD

**Issue by m1n3rva** [ChristianKuehnel/bimmer_connected#59]
based on the discussion in #18:
Implement services in Home Assistant to trigger the remote services of bimmer_connected

**Comment by ChristianKuehnel** [comment]
@gerard33 @m1n3rva 
I completely forgot about the remote services. Thx for the reminder!

Just implemented them. It was actually easier than I expected...
https://github.com/home-assistant/home-assistant/pull/13497
